// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsInventory.Repository;

#nullable disable

namespace ProductsInventory.Api.Migrations
{
    [DbContext(typeof(ProductsInventoryDbContext))]
    [Migration("20250605160238_PatchMigration")]
    partial class PatchMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsInventory.Repository.Models.EndProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InStorage")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EndProducts");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.ProductionProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndProductId");

                    b.ToTable("ProductionProcesses");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InStorage")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.RawMaterialForProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndProductId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("RawMaterialForProductions");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.ShipmentItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndProductId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShippingItems");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.ProductionProcess", b =>
                {
                    b.HasOne("ProductsInventory.Repository.Models.EndProduct", "EndProduct")
                        .WithMany("ProductionProcess")
                        .HasForeignKey("EndProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndProduct");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.RawMaterialForProduction", b =>
                {
                    b.HasOne("ProductsInventory.Repository.Models.EndProduct", "EndProduct")
                        .WithMany("RawMaterialForProduction")
                        .HasForeignKey("EndProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductsInventory.Repository.Models.RawMaterial", "RawMaterial")
                        .WithMany("RawMaterialForProduction")
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndProduct");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.ShipmentItems", b =>
                {
                    b.HasOne("ProductsInventory.Repository.Models.EndProduct", "EndProduct")
                        .WithMany()
                        .HasForeignKey("EndProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductsInventory.Repository.Models.Shipment", "Shipment")
                        .WithMany("Items")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndProduct");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.EndProduct", b =>
                {
                    b.Navigation("ProductionProcess");

                    b.Navigation("RawMaterialForProduction");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.RawMaterial", b =>
                {
                    b.Navigation("RawMaterialForProduction");
                });

            modelBuilder.Entity("ProductsInventory.Repository.Models.Shipment", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
